<?xml version="1.0" ?>
<!--
  Copyright 2016 Pavel Vechersky, ASL, ETH Zurich, Switzerland

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<robot name="tailsitter" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Global properties -->
    <xacro:property name="namespace" value="$(arg namespace)" />
    <xacro:property name="rotor_velocity_slowdown_sim" value="10" />

    <xacro:property name="use_mesh" value="true" />

    <!-- Constants -->
    <xacro:property name="PI" value="3.1415926535897931" />

    <!-- propeller and control surface macros -->
    <xacro:include filename="$(find rotors_description)/urdf/fw_slipstream_base.xacro" />

    <xacro:property name="mass_body" value="0.15" />
    <!-- x->length, y->width, z->height -->
    <xacro:property name="body_length" value="0.6" />
    <xacro:property name="body_width" value="0.06" />
    <xacro:property name="body_height" value="0.2" />
    <xacro:property name="body_mesh_file" value="$(find rotors_gazebo)/models/ts_ethz/meshes/pacflyer_s100_mockup.dae" />
    <xacro:property name="body_mesh_scale_factor" value="${45e-5}" />    
    <xacro:property name="body_mesh_scale" value="${body_mesh_scale_factor} ${body_mesh_scale_factor} ${body_mesh_scale_factor}" />
    <xacro:property name="body_color" value="White" />
    <xacro:property name="body_inertia">
        <inertia ixx="0.000462" ixy="0.0" ixz="0.0" iyy="0.00232" iyz="0.0" izz="0.00187" />
    </xacro:property>


    <!-- main body -->
    <xacro:fixed_wing_slipstream_body robot_namespace="${namespace}" mass="${mass_body}" length="${body_length}" width="${body_width}" height="${body_height}" color="${body_color}" mesh_file="${body_mesh_file}" mesh_scale="${body_mesh_scale}">
<!-- start COM above ground level -->
        <origin xyz="0 0 ${body_length}" rpy="0 0 0" />
        <xacro:insert_block name="body_inertia" />
    </xacro:fixed_wing_slipstream_body>


    <!-- Propeller properties -->
    <xacro:property name="mass_propeller" value="1e-7" /> <!-- [kg] -->
    <xacro:property name="propeller_direction" value="cw" />
    <xacro:property name="propeller_radius" value="0.065" />
    <xacro:property name="propeller_distance" value="0.14" />
    <xacro:property name="propeller_height" value="0.003" />
    <xacro:property name="propeller_color" value="${body_color}" />
    <xacro:property name="propeller_mesh_file" value="package://rotors_description/meshes/propeller_${propeller_direction}.dae" />


    <!-- todo: replace with cylinder intertia(look in fixed_wing_base) -->
    <!-- inertia of a single rotor, assuming it is a cuboid. Height=3mm, width=15mm -->
    <xacro:property name="propeller_inertia">
        <inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6" />
    </xacro:property>

    <!-- left propeller -->
    <xacro:propeller robot_namespace="${namespace}" suffix="left" parent="${namespace}/base_link" mass_propeller="${mass_propeller}" propeller_radius="${propeller_radius}" color="${propeller_color}" use_mesh_file="${use_mesh}" mesh_file="${propeller_mesh_file}">
        <origin xyz="${propeller_distance} 0 ${body_height/2}" rpy="0 0 0" />
        <xacro:insert_block name="propeller_inertia" />
    </xacro:propeller>


    <!-- right propeller -->
    <xacro:propeller robot_namespace="${namespace}" suffix="right" parent="${namespace}/base_link" mass_propeller="${mass_propeller}" propeller_radius="${propeller_radius}" color="${propeller_color}" use_mesh_file="${use_mesh}" mesh_file="${propeller_mesh_file}">
        <origin xyz="0.0 0.195 0.4685" rpy="0 0 0" />
        <xacro:insert_block name="propeller_inertia" />
    </xacro:propeller>


    <!-- elevon(elevator+aileron) control surfaces-->

    <xacro:property name="mass_elevon" value="1e-8" />
    <xacro:property name="elevon_min_angle" value="" />
    <xacro:property name="elevon_length" value="${body_length/2}" />
    <xacro:property name="elevon_width" value="${body_width/3}" />
    <xacro:property name="elevon_height" value="${body_height/4}" />
    <xacro:property name="elevon_min_angle" value="(-30*${PI})/180" />
    <xacro:property name="elevon_max_angle" value="(30*${PI})/180" />
    <xacro:property name="elevon_color" value="${body_color}" />
    <xacro:property name="damping_factor" value="1.0" />
    <xacro:property name="elevon_inertia">
        <inertia ixx="1e-6" iyy="1e-6" izz="1e-6" iyz="0.0" ixz="0.0" ixy="0.0" />
    </xacro:property>

    <xacro:control_surface robot_namespace="${namespace}" surface_name="left_elevon" parent="${namespace}/base_link" mass_surface="${mass_elevon}" min_angle="${elevon_min_angle}" max_angle="${elevon_max_angle}" color="${elevon_color}" use_mesh_file="false" mesh_file="" surface_length="${elevon_length}" surface_width="${elevon_width}" surface_height="${elevon_height}">
        <axis xyz="1 0 0" /> <!-- Joint axis -->
        <origin xyz="0 0 0.03" rpy="0 0 0" /> <!-- Joint origin -->
        <origin xyz="0.0 0.195 0.2365" rpy="0 0 0" /> <!-- Link origin -->
        <xacro:insert_block name="elevon_inertia" />
    </xacro:control_surface>

    <xacro:control_surface robot_namespace="${namespace}" surface_name="right_elevon" parent="${namespace}/base_link" mass_surface="${mass_elevon}" min_angle="${elevon_min_angle}" max_angle="${elevon_max_angle}" color="${elevon_color}" use_mesh_file="false" mesh_file="" surface_length="${elevon_length}" surface_width="${elevon_width}" surface_height="${elevon_height}">
        <axis xyz="0 1 0" /> <!-- Joint axis -->
        <origin xyz="0 0 0.03" rpy="0 0 0" /> <!-- Joint origin -->
        <origin xyz="0.0 -0.195 0.2365" rpy="0 0 0" /> <!-- Link origin -->
        <xacro:insert_block name="elevon_inertia" />
    </xacro:control_surface>
</robot>